<a href="https://colab.research.google.com/github/Fathima-Shifa902/pandas/blob/main/Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY(Numerical python):

numpy is a python library used for working with arrays.

import:import numpy as np




In [ ]:
#list
a=[1,2,3,4]
b=[6,7,8,9]
add=print(a+b)


[1, 2, 3, 4, 6, 7, 8, 9]


In [ ]:
import numpy as np
arr1=np.array([1,2,3,4])     #mathematical use annu numpy
arr2=np.array([6,7,8,9])
result=print(arr1+arr2)

[ 7  9 11 13]


In [ ]:
#position/indexing
arr=[10,20,30,40,50,60,70,80]
print(arr[2])

30


In [ ]:
#slicing
#one dimentional array
arr1=np.array([10,20,30,40,50,60,70,80,90,100])
print(arr1[3:10:2])
print(arr1.ndim)          #ndim used to find dimentions


[ 40  60  80 100]
1


In [ ]:
#2dimensional
arr1=np.array(([10,20,30,40,],[50,60,70,80]))
print(arr1.ndim)



2


In [ ]:
#3dimentional- collection of 2d array
arr1=np.array([[[10,20,30],[40,50,60],[70,80,90]]])
print(arr1.ndim)

3


In [ ]:
arr1=np.array([[[10,20,30],
                 [40,50,60]],

                 [[70,80,90],
                 [100,110,120]]])
print(arr1[1,1,2])

120


In [ ]:
#one dimention convert to 2dimention-reshape
arr1=np.array([1,2,3,4,5,6,7,8])
arr2=arr1.reshape(2,4)
print(arr1)
print(arr2)
print(arr2.shape)     #shape-rows & columns

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [ ]:
#functn-zeros
a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [ ]:
#funcn-ones
b=np.ones(5)
print(b)

[1. 1. 1. 1. 1.]


In [ ]:
#functn-arange
c=np.arange(1,10)  #less than 10 verallu no
print(c)

[1 2 3 4 5 6 7 8 9]


In [ ]:
#functn-linspace
d=np.linspace(0,20,4)    #range koduthappo values athinte ullill vannu
print(d)

[ 0.          6.66666667 13.33333333 20.        ]


In [ ]:
#functn-random
e=np.random.rand(5)
print(e)

[0.8465025  0.84084126 0.0602076  0.36733215 0.78489643]


In [ ]:
import numpy as np
arr1=np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]]])
print(arr1[0,1,2])

6


In [ ]:
arr1=np.array([1,2,3,4,5,6,7,8])
arr2=arr1.reshape(2,4)
print(arr1)
print(arr2)
print(arr2.shape)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


**PANDAS** : (Panel data system)


  *open source python library

  *used for data cleaning,data analysis,data manipulation and data visualization prepration.

  *pandas working with excel sheets or tabular format data.

  *PANDAS DATA STRUCTURE *:

  Pandas has mainly two types
  
  1)series
  
  2)data frame

  **import**:import pandas as pd


SERIES : one dimentional labelled array

In [ ]:
import pandas as pd
marks=pd.Series([1,2,3,4,5])
print(marks)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
import pandas as pd
marks=pd.Series([30,40,50,60],index=["maths","physics","chemistry","english"])
print(marks)

maths        30
physics      40
chemistry    50
english      60
dtype: int64


In [ ]:
import pandas as pd
food=pd.Series([199,299,250,19],index=["shawarma","load fries","shake","mojito"])
print(food)


shawarma      199
load fries    299
shake         250
mojito         19
dtype: int64


In [ ]:
import pandas as pd
name=pd.Series(["bsc","bca","bcom","bba"],index=["shifa","fitha","shann","ardra"])
print(name)


shifa     bsc
fitha     bca
shann    bcom
ardra     bba
dtype: object


In [ ]:
import pandas as pd
name=pd.Series(["bsc","bca","bcom","bba"],index=["shifa","fitha","shann","ardra"])
print(name["shann"])


bcom


1)what is numpy and panda

ans: numpy(numerical python) is a python library used for working with arrays.
     pandas(panel data system) is a open source library,used for data cleaning ,data analysis,data manipulation and data visualization prepration.

2)why do we use numpy and panda

ans: numpy is used for mathematical operations and  working with arrays.

  pandas used for data cleaning,data analysis,data manipulation and data visualization prepration.

3)what is series

ans: one dimensional labelled array.

4)what is the difference b\w list and numpy array

ans: list can store different data types.slower.
numpy can store elements in same data type,faster.

5)what is indexing and slicing

ans)indexing is accesing single element using position.

  slicing is accessing multiple element from a sequence.

In [ ]:
#6)create a numpy array contains no from 1 to 20
a=np.arange(1,21)
print(a)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#7)create a panda series with doc and dep
import pandas as pd
name=pd.Series(["cardiology","radiology","ophthalmology","general"],index=["alex","adam","shaharsha","shamin"])
print(name)

alex            cardiology
adam             radiology
shaharsha    ophthalmology
shamin             general
dtype: object
